import type { AIDecisionProcess, AICompetitor, AnalysisMatch, Combination, CommunityPost, FeaturedMatch } from "./types";

export const aiCompetitors: AICompetitor[] = [
  {
    id: "gpt",
    name: "GPT",
    initials: "GP",
    analysisStyle: "데이터 분석형",
    investmentPhilosophy: "높은 적중률을 우선하는 안정적인 전략",
    signatureTraits: ["최근 경기 데이터", "선발투수", "팀 전력", "평균 득점"],
    strategy: "데이터 안정형",
    strategyDescription: "리스크를 줄이는 선택을 선호하지만, 상황에 따라 3~5폴더 조합 가능",
    bestHitCombination: "EPL + KBO + LCK 판단 조합",
    bestHitOdds: 7.18,
    startingBalance: 1000,
    currentBalance: 1286,
    totalProfit: 286,
    roi: 28.6,
    accuracy: 64.7,
    totalPicks: 17,
    wins: 11,
    losses: 6,
    battleWins: 42,
    battleLosses: 28,
    recentResults: ["적중", "적중", "미적중", "적중", "미적중"],
  },
  {
    id: "gemini",
    name: "Gemini",
    initials: "GE",
    analysisStyle: "균형 분석형",
    investmentPhilosophy: "흐름과 데이터를 함께 고려하는 전략",
    signatureTraits: ["최근 경기 흐름", "홈/원정", "선수 컨디션", "공수 밸런스"],
    strategy: "균형 분석형",
    strategyDescription: "수익률과 적중 가능성을 함께 고려해 3~5폴더 조합 가능",
    bestHitCombination: "KBO + EPL + LCK 판단 조합",
    bestHitOdds: 10.64,
    startingBalance: 1000,
    currentBalance: 1168,
    totalProfit: 168,
    roi: 16.8,
    accuracy: 58.8,
    totalPicks: 17,
    wins: 10,
    losses: 7,
    battleWins: 38,
    battleLosses: 32,
    recentResults: ["미적중", "적중", "적중", "적중", "미적중"],
  },
  {
    id: "deepseek",
    name: "DeepSeek",
    initials: "DS",
    analysisStyle: "가치 탐색형",
    investmentPhilosophy: "시장과 다른 기회를 찾는 전략",
    signatureTraits: ["배당 가치", "시장 과열", "숨은 변수", "업셋 가능성"],
    strategy: "변동성 탐색형",
    strategyDescription: "배당 매력이 있는 조합을 적극 검토하지만, 3~5폴더 안에서 자유롭게 구성",
    bestHitCombination: "KBO + EPL + LCK 판단 조합",
    bestHitOdds: 15.34,
    startingBalance: 1000,
    currentBalance: 937,
    totalProfit: -63,
    roi: -6.3,
    accuracy: 47.1,
    totalPicks: 17,
    wins: 8,
    losses: 9,
    battleWins: 35,
    battleLosses: 35,
    recentResults: ["적중", "미적중", "미적중", "적중", "미적중"],
  },
];

export const decisionProcesses: AIDecisionProcess[] = [
  {
    aiName: "GPT",
    reviewedMatches: 84,
    candidateMatches: 12,
    finalSelections: 3,
    excludedMatches: 72,
    combinationOdds: 4.85,
  },
  {
    aiName: "Gemini",
    reviewedMatches: 84,
    candidateMatches: 15,
    finalSelections: 5,
    excludedMatches: 69,
    combinationOdds: 16.58,
  },
  {
    aiName: "DeepSeek",
    reviewedMatches: 84,
    candidateMatches: 18,
    finalSelections: 3,
    excludedMatches: 66,
    combinationOdds: 5.88,
  },
];

export const analysisMatches: AnalysisMatch[] = [
  {
    id: "lg-kia",
    match: "LG Twins vs KIA Tigers",
    sport: "야구",
    league: "KBO",
    startTime: "2026-06-01 18:30",
    headline: "선발 매치업과 불펜 변수가 갈리는 KBO 핵심 경기",
    consensusScore: 67,
    consensusLabel: "Partial Consensus",
    actualResult: "LG 승",
    analyses: [
      {
        aiName: "GPT",
        prediction: "LG 승",
        confidence: 58,
        roiChange: 145,
        analysisAngle: "최근 승률 기반 분석",
        decisionStatus: "조합 포함",
        decisionReason: "최근 승률 우세와 선발 매치업 신뢰도가 높아 최종 조합에 포함했습니다.",
        summary: "최근 선발투수 지표와 중심 타선 흐름에서 LG가 근소하게 앞섭니다.",
        strengths: ["선발 우위", "상위 타선 출루율 상승"],
        risks: ["불펜 소모", "초반 실점 변수"],
      },
      {
        aiName: "Gemini",
        prediction: "KIA 승",
        confidence: 57,
        roiChange: -100,
        analysisAngle: "최근 팀 흐름 기반 분석",
        decisionStatus: "조합 포함",
        decisionReason: "최근 득점력과 후반 집중력을 근거로 반대 방향 가치가 있다고 판단했습니다.",
        summary: "최근 팀 타격 상승세와 후반 집중력을 고려하면 KIA가 근소하게 승부를 뒤집을 여지가 있습니다.",
        strengths: ["최근 팀 타격 상승", "후반 집중력"],
        risks: ["선발 매치업 열세", "초반 실점 변수"],
      },
      {
        aiName: "DeepSeek",
        prediction: "LG 승",
        confidence: 55,
        roiChange: 122,
        analysisAngle: "배당 가치 기반 분석",
        decisionStatus: "최종 제외",
        decisionReason: "배당 가치는 보였지만 전력 열세와 변동성이 커 최종 조합에서는 제외했습니다.",
        summary: "시장 관심이 KIA 쪽 변동성에 쏠렸지만, 배당 대비 LG의 기본 전력 가치가 더 남아 있습니다.",
        strengths: ["배당 가치 존재", "기본 전력 우위"],
        risks: ["불펜 변수", "상대 타선 반등"],
      },
    ],
  },
  {
    id: "hanwha-lotte",
    match: "한화 Eagles vs 롯데 Giants",
    sport: "야구",
    league: "KBO",
    startTime: "2026-06-01 18:30",
    headline: "득점 흐름은 좋지만 총점 라인이 관건인 경기",
    consensusScore: 100,
    consensusLabel: "Strong Consensus",
    analyses: [
      {
        aiName: "GPT",
        prediction: "언더 8.5",
        confidence: 54,
        analysisAngle: "실점 지표 기반 분석",
        decisionStatus: "후보만 선정",
        decisionReason: "실점 지표는 안정적이지만 불펜 변수 때문에 최종 선택까지는 가지 않았습니다.",
        summary: "양 팀 선발이 초반 실점을 억제할 가능성이 있어 언더 쪽을 우선합니다.",
        strengths: ["선발 안정감", "초반 득점 억제"],
        risks: ["불펜 난조", "수비 실책"],
      },
      {
        aiName: "Gemini",
        prediction: "언더 8.5",
        confidence: 54,
        analysisAngle: "최근 득점 흐름 기반 분석",
        decisionStatus: "조합 포함",
        decisionReason: "득점 흐름은 좋지만 총점 라인이 높아 언더 쪽 기대값을 선택했습니다.",
        summary: "최근 득점 흐름은 좋지만 양 팀 선발 이닝 소화 가능성을 함께 보면 총점 언더가 더 균형 잡힌 선택입니다.",
        strengths: ["선발 이닝 소화", "초반 탐색전 가능성"],
        risks: ["후반 불펜 난조", "장타 변수"],
      },
      {
        aiName: "DeepSeek",
        prediction: "언더 8.5",
        confidence: 57,
        analysisAngle: "총점 라인 가치 분석",
        decisionStatus: "조합 포함",
        decisionReason: "총점 라인 대비 언더 가치가 뚜렷해 조합에 포함했습니다.",
        summary: "라인 대비 득점 기대치가 낮아 총점 언더를 더 매력적으로 봅니다.",
        strengths: ["총점 라인 가치", "초반 투수전 가능성"],
        risks: ["후반 빅이닝", "제구 난조"],
      },
    ],
  },
  {
    id: "t1-gen",
    match: "T1 vs GEN",
    sport: "e스포츠",
    league: "LCK",
    startTime: "2026-06-01 20:00",
    headline: "밴픽 방향에 따라 AI 의견이 갈리는 LCK 빅매치",
    consensusScore: 67,
    consensusLabel: "Partial Consensus",
    analyses: [
      {
        aiName: "GPT",
        prediction: "T1 승",
        confidence: 56,
        analysisAngle: "오브젝트 지표 기반 분석",
        decisionStatus: "조합 포함",
        decisionReason: "초반 오브젝트 지표와 교전 전환 기대값이 높아 선택했습니다.",
        summary: "초반 오브젝트 설계와 교전 전환 속도에서 T1의 기대값이 높습니다.",
        strengths: ["초반 설계", "교전 전환"],
        risks: ["후반 운영", "드래프트 변수"],
      },
      {
        aiName: "Gemini",
        prediction: "GEN 승",
        confidence: 53,
        analysisAngle: "최근 운영 흐름 기반 분석",
        decisionStatus: "조합 포함",
        decisionReason: "운영 안정성과 최근 맞대결 흐름을 근거로 최종 선택했습니다.",
        summary: "최근 맞대결 기준 GEN의 안정적인 운영 완성도가 더 높게 평가됩니다.",
        strengths: ["운영 안정성", "후반 집중력"],
        risks: ["초반 손실", "밴픽 꼬임"],
      },
      {
        aiName: "DeepSeek",
        prediction: "GEN 승",
        confidence: 52,
        analysisAngle: "밴픽 변수 가치 분석",
        decisionStatus: "조합 포함",
        decisionReason: "밴픽 변수에도 배당 대비 기대값이 남아 조합에 포함했습니다.",
        summary: "시장 기대보다 GEN의 밴픽 대응력과 후반 운영 안정성이 더 크게 반영될 가능성이 있습니다.",
        strengths: ["밴픽 대응력", "후반 운영 안정성"],
        risks: ["초반 주도권 상실", "변칙 픽 대응"],
      },
    ],
  },
  {
    id: "mancity-liverpool",
    match: "맨시티 vs 리버풀",
    sport: "축구",
    league: "EPL",
    startTime: "2026-06-01 21:30",
    headline: "압박 강도와 전환 속도가 승부를 가를 EPL 메인 매치",
    consensusScore: 67,
    consensusLabel: "Partial Consensus",
    analyses: [
      {
        aiName: "GPT",
        prediction: "맨시티 승",
        confidence: 59,
        analysisAngle: "팀 전력 지표 기반 분석",
        decisionStatus: "조합 포함",
        decisionReason: "홈 경기 전력 지표와 찬스 생성 수치가 우세해 선택했습니다.",
        summary: "홈 점유율과 박스 근처 찬스 생성 빈도에서 맨시티 우세를 봅니다.",
        strengths: ["홈 점유율", "중앙 침투"],
        risks: ["역습 실점", "세트피스 수비"],
      },
      {
        aiName: "Gemini",
        prediction: "맨시티 승",
        confidence: 57,
        analysisAngle: "공격 흐름 기반 분석",
        decisionStatus: "조합 포함",
        decisionReason: "공격 흐름과 득점 기대값이 좋아 최종 조합에 넣었습니다.",
        summary: "양 팀 모두 전환 속도가 빨라 득점 기대값이 높습니다.",
        strengths: ["높은 득점 기대값", "빠른 전환"],
        risks: ["초반 탐색전", "결정력 저하"],
      },
      {
        aiName: "DeepSeek",
        prediction: "무승부",
        confidence: 52,
        analysisAngle: "시장 과열 역방향 분석",
        decisionStatus: "후보만 선정",
        decisionReason: "시장 과열 반대 관점은 유효하지만 승부 변수가 커 후보로만 남겼습니다.",
        summary: "리버풀의 압박 회복력이 핸디캡 시장에서 가치가 있습니다.",
        strengths: ["전방 압박", "핸디캡 가치"],
        risks: ["수비 뒷공간", "원정 변수"],
      },
    ],
  },
  {
    id: "kt-ssg",
    match: "KT Wiz vs SSG Landers",
    sport: "야구",
    league: "KBO",
    startTime: "2026-06-01 18:30",
    headline: "승패보다 핸디캡 해석이 중요한 KBO 경기",
    consensusScore: 67,
    consensusLabel: "Partial Consensus",
    analyses: [
      {
        aiName: "GPT",
        prediction: "SSG +1.5",
        confidence: 56,
        analysisAngle: "핸디캡 안정성 분석",
        decisionStatus: "후보만 선정",
        decisionReason: "접전 가능성은 높지만 조합 내 우선순위에서 밀려 후보로 분류했습니다.",
        summary: "접전 흐름 가능성이 높아 핸디캡 접근이 더 안정적입니다.",
        strengths: ["접전 가능성", "불펜 뎁스"],
        risks: ["초반 대량 실점", "타선 침묵"],
      },
      {
        aiName: "Gemini",
        prediction: "SSG +1.5",
        confidence: 55,
        analysisAngle: "후반 추격 흐름 분석",
        decisionStatus: "조합 포함",
        decisionReason: "후반 추격력과 핸디캡 안정성을 높게 평가해 조합에 포함했습니다.",
        summary: "최근 실점 관리가 개선되어 큰 점수 차 패배 가능성은 낮게 봅니다.",
        strengths: ["실점 관리", "후반 추격력"],
        risks: ["선발 제구", "득점권 부진"],
      },
      {
        aiName: "DeepSeek",
        prediction: "KT 승",
        confidence: 53,
        analysisAngle: "승패 시장 가치 분석",
        decisionStatus: "조합 포함",
        decisionReason: "상위 타선 기대값과 시장 배당 가치가 맞아 선택했습니다.",
        summary: "KT의 상위 타선 기대값이 승패 시장에서 살아 있습니다.",
        strengths: ["상위 타선", "홈 분위기"],
        risks: ["불펜 변수", "핸디캡 부담"],
      },
    ],
  },
];

export const combinations: Combination[] = [
  {
    id: "combo-001",
    date: "2026-06-01",
    aiName: "GPT",
    style: "데이터 안정형",
    stake: 100,
    totalOdds: 4.85,
    potentialReturn: 485,
    status: "대기중",
    result: "경기 전",
    profit: 0,
    selections: [
      { analysisId: "lg-kia", match: "LG Twins vs KIA Tigers", league: "KBO", sport: "야구", prediction: "LG 승", odds: 1.55 },
      { analysisId: "mancity-liverpool", match: "맨시티 vs 리버풀", league: "EPL", sport: "축구", prediction: "맨시티 승", odds: 1.72 },
      { analysisId: "t1-gen", match: "T1 vs GEN", league: "LCK", sport: "e스포츠", prediction: "T1 승", odds: 1.82 },
    ],
  },
  {
    id: "combo-002",
    date: "2026-06-01",
    aiName: "Gemini",
    style: "균형 분석형",
    stake: 100,
    totalOdds: 16.58,
    potentialReturn: 1658,
    status: "대기중",
    result: "경기 전",
    profit: 0,
    selections: [
      { analysisId: "lg-kia", match: "LG Twins vs KIA Tigers", league: "KBO", sport: "야구", prediction: "KIA 승", odds: 2.05 },
      { analysisId: "mancity-liverpool", match: "맨시티 vs 리버풀", league: "EPL", sport: "축구", prediction: "맨시티 승", odds: 1.72 },
      { analysisId: "t1-gen", match: "T1 vs GEN", league: "LCK", sport: "e스포츠", prediction: "GEN 승", odds: 2.05 },
      { analysisId: "kt-ssg", match: "KT Wiz vs SSG Landers", league: "KBO", sport: "야구", prediction: "SSG +1.5", odds: 1.22 },
      { analysisId: "hanwha-lotte", match: "한화 Eagles vs 롯데 Giants", league: "KBO", sport: "야구", prediction: "언더 8.5", odds: 1.88 },
    ],
  },
  {
    id: "combo-003",
    date: "2026-06-01",
    aiName: "DeepSeek",
    style: "변동성 탐색형",
    stake: 100,
    totalOdds: 5.88,
    potentialReturn: 588,
    status: "대기중",
    result: "경기 전",
    profit: 0,
    selections: [
      { analysisId: "kt-ssg", match: "KT Wiz vs SSG Landers", league: "KBO", sport: "야구", prediction: "KT 승", odds: 2.1 },
      { analysisId: "hanwha-lotte", match: "한화 Eagles vs 롯데 Giants", league: "KBO", sport: "야구", prediction: "언더 8.5", odds: 1.88 },
      { analysisId: "t1-gen", match: "T1 vs GEN", league: "LCK", sport: "e스포츠", prediction: "GEN 승", odds: 1.49 },
    ],
  },
];

const historyCombinations: Combination[] = [
  {
    ...combinations[0],
    id: "combo-004",
    date: "2026-05-31",
    status: "적중",
    result: "4/4 적중",
    totalOdds: 7.18,
    potentialReturn: 718,
    profit: 618,
    selections: [
      ...combinations[0].selections,
      { analysisId: "kt-ssg", match: "SSG Landers vs NC Dinos", league: "KBO", sport: "야구", prediction: "SSG 승", odds: 1.68 },
    ],
  },
  {
    ...combinations[1],
    id: "combo-005",
    date: "2026-05-31",
    status: "미적중",
    result: "2/3 적중",
    totalOdds: 6.92,
    potentialReturn: 692,
    profit: -100,
    selections: combinations[1].selections.slice(0, 3),
  },
  {
    ...combinations[2],
    id: "combo-006",
    date: "2026-05-31",
    status: "미적중",
    result: "3/4 적중",
    totalOdds: 9.24,
    potentialReturn: 924,
    profit: -100,
    selections: [
      ...combinations[2].selections,
      { analysisId: "mancity-liverpool", match: "맨시티 vs 리버풀", league: "EPL", sport: "축구", prediction: "리버풀 +1.0", odds: 1.36 },
    ],
  },
  {
    ...combinations[0],
    id: "combo-007",
    date: "2026-05-30",
    status: "적중",
    result: "5/5 적중",
    totalOdds: 9.08,
    potentialReturn: 908,
    profit: 808,
    selections: [
      ...combinations[0].selections,
      { analysisId: "hanwha-lotte", match: "한화 Eagles vs 롯데 Giants", league: "KBO", sport: "야구", prediction: "언더 8.5", odds: 1.44 },
      { analysisId: "kt-ssg", match: "KT Wiz vs SSG Landers", league: "KBO", sport: "야구", prediction: "SSG +1.5", odds: 1.57 },
    ],
  },
  {
    ...combinations[1],
    id: "combo-008",
    date: "2026-05-30",
    status: "적중",
    result: "4/4 적중",
    totalOdds: 8.72,
    potentialReturn: 872,
    profit: 772,
    selections: combinations[1].selections.slice(0, 4),
  },
  {
    ...combinations[2],
    id: "combo-009",
    date: "2026-05-30",
    status: "적중",
    result: "5/5 적중",
    totalOdds: 15.34,
    potentialReturn: 1534,
    profit: 1434,
    selections: [
      ...combinations[2].selections,
      { analysisId: "mancity-liverpool", match: "토트넘 vs 아스널", league: "EPL", sport: "축구", prediction: "무승부", odds: 3.2 },
      { analysisId: "lg-kia", match: "LG Twins vs KIA Tigers", league: "KBO", sport: "야구", prediction: "LG 승", odds: 1.55 },
    ],
  },
];

export const allCombinations: Combination[] = [...combinations, ...historyCombinations];

export const featuredMatches: FeaturedMatch[] = analysisMatches.map((match) => ({
  id: match.id,
  sport: match.sport,
  league: match.league,
  match: match.match,
  startTime: match.startTime,
}));

export const communityPosts: CommunityPost[] = [
  {
    id: "post-001",
    category: "AI토론",
    title: "오늘 DeepSeek가 의외로 3폴더만 간 이유가 뭘까요?",
    author: "LineWatcher",
    createdAt: "2026-06-01 10:24",
    views: 482,
    comments: 12,
    likes: 36,
    body: "평소보다 조합 배당이 낮아서 놀랐습니다. T1과 KT 쪽은 이해되는데, 언더까지 묶은 판단은 꽤 조심스러워 보여요.",
    commentList: [
      { id: "c-001", author: "PitchMap", createdAt: "2026-06-01 10:41", content: "오늘 KBO 라인이 애매해서 변동성을 줄인 것 같습니다." },
      { id: "c-002", author: "AIReader", createdAt: "2026-06-01 11:02", content: "DeepSeek도 매번 공격적으로만 가는 건 아니라는 점이 좋네요." },
    ],
  },
  {
    id: "post-002",
    category: "경기분석",
    title: "LG vs KIA는 AI 의견이 갈리는 게 핵심",
    author: "BullpenNote",
    createdAt: "2026-06-01 09:18",
    views: 719,
    comments: 18,
    likes: 44,
    body: "GPT와 Gemini는 LG를 보고, DeepSeek는 KIA 배당 가치를 봅니다. 승패보다 후반 불펜 변수를 봐야 할 경기 같습니다.",
    commentList: [
      { id: "c-003", author: "KBOFlow", createdAt: "2026-06-01 09:47", content: "저도 KIA 쪽 배당 가치는 있다고 봅니다." },
    ],
  },
  {
    id: "post-003",
    category: "픽공유",
    title: "오늘은 Gemini 5폴더를 소액으로 따라가 봅니다",
    author: "ComboLab",
    createdAt: "2026-06-01 08:33",
    views: 333,
    comments: 7,
    likes: 21,
    body: "배당은 높지만 선택들이 완전히 무리한 느낌은 아니라서 소액 참고용으로 괜찮아 보입니다.",
    commentList: [
      { id: "c-004", author: "GreenTicket", createdAt: "2026-06-01 08:58", content: "GEN 승이 제일 변수 같아요." },
    ],
  },
  {
    id: "post-004",
    category: "질문답변",
    title: "AI 조합 배당은 각 선택 배당을 곱한 값인가요?",
    author: "NewUser",
    createdAt: "2026-05-31 22:10",
    views: 205,
    comments: 5,
    likes: 9,
    body: "조합 배당 계산 방식이 궁금합니다. 실제 배팅이 아니라 콘텐츠용 수치인 건 이해했습니다.",
    commentList: [
      { id: "c-005", author: "AdminMock", createdAt: "2026-05-31 22:21", content: "MVP에서는 더미데이터지만, 구조는 선택 배당의 조합 배당을 기준으로 잡았습니다." },
    ],
  },
  {
    id: "post-005",
    category: "자유게시판",
    title: "AI 리그 시즌제로 가면 재밌을 듯",
    author: "SeasonMaker",
    createdAt: "2026-05-31 19:04",
    views: 156,
    comments: 3,
    likes: 14,
    body: "월간 시즌, 종목별 시즌, 플레이오프 같은 식으로 가면 AI별 캐릭터가 더 잘 보일 것 같습니다.",
    commentList: [
      { id: "c-006", author: "LeagueFan", createdAt: "2026-05-31 19:20", content: "종목별 랭킹은 꼭 있었으면 합니다." },
    ],
  },
];

export const getRankedAis = () =>
  [...aiCompetitors].sort((a, b) => b.currentBalance - a.currentBalance);

export const getTodayCombinations = () =>
  combinations.filter((combination) => combination.status === "대기중");

export const getSettledCombinations = () =>
  allCombinations.filter((combination) => combination.status !== "대기중");

export const getAverageRoi = () =>
  aiCompetitors.reduce((total, ai) => total + ai.roi, 0) / aiCompetitors.length;

export const getAnalysisMatch = (id: string) =>
  analysisMatches.find((match) => match.id === id);

export const getMostDivisiveMatch = () =>
  [...analysisMatches].sort((a, b) => a.consensusScore - b.consensusScore)[0];

export const getStrongConsensusMatch = () =>
  [...analysisMatches].sort((a, b) => b.consensusScore - a.consensusScore)[0];
