import { createHash } from "node:crypto";
import { confidenceStake, getAiBalances, DEFAULT_AI_BALANCE } from "@/lib/stake";

const MIN_LEGS = 2;
const MAX_PARLAYS_PER_AI_PER_DAY = 4;

function validPick(pick) {
  const confidence = Number(pick.confidence);
  const odds = Number(pick.odds_used);
  return (
    pick.game_id &&
    Number.isFinite(confidence) &&
    Number.isFinite(odds) &&
    odds > 1
  );
}

function uniqueCombinations(picks, favorCombinations) {
  const sorted = [...picks].filter(validPick).sort((a, b) => Number(b.confidence) - Number(a.confidence));
  if (sorted.length < MIN_LEGS) return [];

  const strong = sorted.filter((pick) => Number(pick.confidence) >= 70);
  const qualified = sorted.filter((pick) => Number(pick.confidence) >= (favorCombinations ? 50 : 60)).slice(0, 4);
  const candidates = [];
  for (let first = 0; first < qualified.length; first += 1) {
    for (let second = first + 1; second < qualified.length; second += 1) {
      candidates.push([qualified[first], qualified[second]]);
    }
  }
  if (strong.length >= 3) candidates.unshift(strong.slice(0, 3));
  else if (favorCombinations && qualified.length >= 3) candidates.unshift(qualified.slice(0, 3));
  const seen = new Set();

  return candidates.filter((combination) => {
    if (combination.length < MIN_LEGS) return false;
    const key = combination.map((pick) => pick.game_id).sort().join(":");
    if (seen.has(key)) return false;
    seen.add(key);
    return true;
  }).slice(0, MAX_PARLAYS_PER_AI_PER_DAY);
}

function totalOdds(picks) {
  return Number(picks.reduce((total, pick) => total * Number(pick.odds_used), 1).toFixed(4));
}

function stakeFor(picks, balance, seed) {
  const averageConfidence = picks.reduce((sum, pick) => sum + Number(pick.confidence), 0) / picks.length;
  return {
    stake: confidenceStake(averageConfidence, { balance, seed, aiModel: picks[0]?.ai_model }),
    averageConfidence: Number(averageConfidence.toFixed(1)),
  };
}

function signatureFor(picks) {
  return createHash("sha256")
    .update(picks.map((pick) => `${pick.game_id}:${pick.market_type ?? "moneyline"}:${pick.pick_type ?? ""}:${pick.line_value ?? ""}`).sort().join("|"))
    .digest("hex")
    .slice(0, 24);
}

async function createParlay(supabase, aiModel, combination, betDate, isAutoGenerated, balance) {
  const signature = signatureFor(combination);
  const { data: existing, error: existingError } = await supabase
    .from("parlays")
    .select("id")
    .eq("ai_model", aiModel)
    .eq("bet_date", betDate)
    .eq("signature", signature)
    .maybeSingle();

  if (existingError) throw new Error(`Failed to check existing parlay: ${existingError.message}`);
  if (existing) return { status: "skipped", id: existing.id };

  const stakeDetails = stakeFor(combination, balance, `${aiModel}:${betDate}:${signature}`);
  const values = {
    ai_model: aiModel,
    stake: stakeDetails.stake,
    total_odds: totalOdds(combination),
    status: "pending",
    bet_date: betDate,
    signature,
    is_auto_generated: isAutoGenerated,
  };
  const { data: parlay, error: parlayError } = await supabase.from("parlays").insert(values).select("id").single();
  if (parlayError) throw new Error(`Failed to create parlay: ${parlayError.message}`);

  const legs = combination.map((pick, index) => ({
    parlay_id: parlay.id,
    game_id: pick.game_id,
    ai_model: aiModel,
    leg_order: index,
  }));
  const { error: legsError } = await supabase.from("parlay_legs").insert(legs);
  if (legsError) {
    await supabase.from("parlays").delete().eq("id", parlay.id);
    throw new Error(`Failed to create parlay legs: ${legsError.message}`);
  }

  return { status: "created", id: parlay.id, legs: legs.length, average_confidence: stakeDetails.averageConfidence, ...values };
}

function fallbackCandidate(byModel) {
  return [...byModel.entries()]
    .map(([aiModel, picks]) => {
      const distinctGames = new Map();
      for (const pick of [...picks].filter(validPick).sort((a, b) => Number(b.confidence) - Number(a.confidence))) {
        if (!distinctGames.has(pick.game_id)) distinctGames.set(pick.game_id, pick);
      }
      const ranked = [...distinctGames.values()];
      const topPicks = ranked.slice(0, MIN_LEGS);
      const averageConfidence = topPicks.length
        ? topPicks.reduce((sum, pick) => sum + Number(pick.confidence), 0) / topPicks.length
        : 0;
      return { aiModel, picks: topPicks, averageConfidence, topConfidence: Number(ranked[0]?.confidence ?? 0) };
    })
    .filter((candidate) => candidate.picks.length >= MIN_LEGS)
    .sort((a, b) => b.averageConfidence - a.averageConfidence || b.topConfidence - a.topConfidence || a.aiModel.localeCompare(b.aiModel))[0];
}

export async function generateParlays(supabase, { since = new Date(new Date().setUTCHours(0, 0, 0, 0)), favorCombinations = false, aiBalances } = {}) {
  const balances = aiBalances ?? await getAiBalances(supabase);
  const { data: picks, error: picksError } = await supabase
    .from("picks")
    .select("game_id,ai_model,confidence,odds_used,market_type,pick_type,line_value,created_at")
    .gte("created_at", since.toISOString())
    .is("settled_at", null);

  if (picksError) throw new Error(`Failed to fetch parlay candidates: ${picksError.message}`);

  const gameIds = [...new Set((picks ?? []).map((pick) => pick.game_id))];
  if (!gameIds.length) return { candidates: 0, created: 0, skipped: 0, parlays: [], minimum_guarantee: { attempted: true, created: false, reason: "no_ai_with_two_valid_picks" } };

  const { data: games, error: gamesError } = await supabase
    .from("games")
    .select("id,status,commence_time")
    .in("id", gameIds)
    .eq("status", "upcoming")
    .gte("commence_time", new Date().toISOString());

  if (gamesError) throw new Error(`Failed to validate parlay games: ${gamesError.message}`);
  const upcomingIds = new Set((games ?? []).map((game) => game.id));
  const eligible = (picks ?? []).filter((pick) => upcomingIds.has(pick.game_id));
  const byModel = new Map();
  for (const pick of eligible) byModel.set(pick.ai_model, [...(byModel.get(pick.ai_model) ?? []), pick]);

  const result = { candidates: 0, created: 0, skipped: 0, parlays: [], minimum_guarantee: null };
  const betDate = new Date().toISOString().slice(0, 10);
  const { data: dailyParlays, error: dailyParlaysError } = await supabase.from("parlays").select("ai_model").eq("bet_date", betDate);
  if (dailyParlaysError) throw new Error(`Failed to count daily parlays: ${dailyParlaysError.message}`);
  const dailyParlayCounts = new Map();
  for (const parlay of dailyParlays ?? []) dailyParlayCounts.set(parlay.ai_model, (dailyParlayCounts.get(parlay.ai_model) ?? 0) + 1);

  for (const [aiModel, modelPicks] of byModel) {
    const remainingSlots = Math.max(0, MAX_PARLAYS_PER_AI_PER_DAY - (dailyParlayCounts.get(aiModel) ?? 0));
    for (const combination of uniqueCombinations(modelPicks, favorCombinations).slice(0, remainingSlots)) {
      result.candidates += 1;
      const created = await createParlay(supabase, aiModel, combination, betDate, false, balances.get(aiModel) ?? DEFAULT_AI_BALANCE);
      if (created.status === "skipped") {
        result.skipped += 1;
        continue;
      }
      result.created += 1;
      dailyParlayCounts.set(aiModel, (dailyParlayCounts.get(aiModel) ?? 0) + 1);
      result.parlays.push(created);
    }
  }

  const { count: todaysParlayCount, error: countError } = await supabase
    .from("parlays")
    .select("id", { count: "exact", head: true })
    .eq("bet_date", betDate);
  if (countError) throw new Error(`Failed to check daily parlay minimum: ${countError.message}`);

  if ((todaysParlayCount ?? 0) > 0) {
    result.minimum_guarantee = { attempted: false, created: false, reason: result.created > 0 ? "autonomous_parlay_created" : "daily_parlay_already_exists" };
    return { ...result, strategy: { favor_combinations: favorCombinations, max_parlays_per_ai_per_day: MAX_PARLAYS_PER_AI_PER_DAY } };
  }

  const fallback = fallbackCandidate(byModel);
  if (!fallback) {
    result.minimum_guarantee = { attempted: true, created: false, reason: "no_ai_with_two_valid_picks" };
    return { ...result, strategy: { favor_combinations: favorCombinations, max_parlays_per_ai_per_day: MAX_PARLAYS_PER_AI_PER_DAY } };
  }

  const forced = await createParlay(supabase, fallback.aiModel, fallback.picks, betDate, true, balances.get(fallback.aiModel) ?? DEFAULT_AI_BALANCE);
  if (forced.status === "created") {
    result.created += 1;
    result.parlays.push(forced);
  } else {
    result.skipped += 1;
  }
  result.minimum_guarantee = {
    attempted: true,
    created: forced.status === "created",
    reason: forced.status === "created" ? "forced_top_two_confidence_picks" : "fallback_already_exists",
    ai_model: fallback.aiModel,
    confidences: fallback.picks.map((pick) => Number(pick.confidence)),
  };

  return { ...result, strategy: { favor_combinations: favorCombinations, max_parlays_per_ai_per_day: MAX_PARLAYS_PER_AI_PER_DAY } };
}
