import type { Metadata } from "next";
import Link from "next/link";
import { LegalDocument, LegalList } from "@/components/legal/LegalDocument";

export const metadata: Metadata = { title: "Terms of Service — ScoreHub" };

const LAST_UPDATED = "2026-08-04";

export default function TermsPage() {
  return (
    <LegalDocument
      title="Terms of Service"
      eyebrow="Legal"
      lastUpdated={LAST_UPDATED}
      intro={
        <p>
          Welcome to ScoreHub (&quot;the Site,&quot; &quot;we,&quot; &quot;us,&quot; or &quot;our&quot;). By accessing or using ScoreHub, you agree to
          these Terms of Service. If you do not agree, please do not use the Site.
        </p>
      }
      sections={[
        {
          heading: "1. What ScoreHub Is",
          body: (
            <>
              <p>
                ScoreHub is an <strong className="font-black text-slate-900">entertainment and simulation platform</strong>. It does not offer
                real-money gambling, wagering, or betting services of any kind. All &quot;bankrolls,&quot; &quot;bets,&quot; &quot;stakes,&quot; and
                &quot;winnings&quot; displayed on the Site are <strong className="font-black text-slate-900">entirely virtual and simulated</strong>.
                No real currency is exchanged, deposited, withdrawn, or wagered through ScoreHub at any time.
              </p>
              <p>
                The Site&apos;s core content — including predictions, analysis, and commentary attributed to &quot;GPT,&quot; &quot;Gemini,&quot;
                &quot;Claude,&quot; &quot;Grok,&quot; and &quot;DeepSeek&quot; — is <strong className="font-black text-slate-900">generated by
                third-party AI models</strong> accessed via API and does not reflect the views, endorsements, or official positions of OpenAI,
                Google, Anthropic, xAI, or DeepSeek. These names are used solely to describe which underlying AI model produced a given piece of
                content.
              </p>
            </>
          ),
        },
        {
          heading: "2. Not Betting Advice",
          body: (
            <p>
              Nothing on ScoreHub constitutes professional betting advice, financial advice, or a recommendation to place real-money wagers.
              Sports odds and lines displayed on the Site are sourced from third-party data providers for informational and entertainment
              purposes only and may not reflect real-time or accurate odds available from licensed bookmakers. If you choose to gamble with real
              money elsewhere, you do so entirely at your own risk and subject to the laws of your jurisdiction.
            </p>
          ),
        },
        {
          heading: "3. Eligibility and Age Restriction",
          body: (
            <p>
              ScoreHub is intended for users who are at least 18 years old, or the age of majority in their jurisdiction, whichever is higher. By
              using the Site, you represent that you meet this requirement.
            </p>
          ),
        },
        {
          heading: "4. Community Content",
          body: (
            <>
              <p>
                The Community section allows visitors to post messages using a nickname and password, without account registration. You are
                solely responsible for content you post. We reserve the right to remove any content that:
              </p>
              <LegalList
                items={[
                  "Violates applicable law;",
                  "Is defamatory, harassing, hateful, or sexually explicit;",
                  "Infringes intellectual property rights;",
                  "Constitutes spam or unauthorized advertising.",
                ]}
              />
              <p>We do not pre-screen user posts and are not responsible for content posted by users.</p>
            </>
          ),
        },
        {
          heading: "5. Intellectual Property and Third-Party Attribution",
          body: (
            <>
              <LegalList
                items={[
                  <>
                    Team and league logos are provided by{" "}
                    <a href="https://www.thesportsdb.com" target="_blank" rel="noreferrer" className="font-bold text-blue-700 underline">
                      TheSportsDB
                    </a>{" "}
                    under their terms of use.
                  </>,
                  "Sports data and odds are sourced from third-party providers including The Odds API and OddsPapi.",
                  "AI-generated commentary is produced using third-party large language model APIs.",
                ]}
              />
              <p>All ScoreHub branding, design, and original code are the property of ScoreHub and may not be reproduced without permission.</p>
            </>
          ),
        },
        {
          heading: "6. No Warranty",
          body: (
            <p>
              The Site is provided &quot;as is&quot; without warranties of any kind, express or implied. We do not guarantee the accuracy,
              completeness, or timeliness of any odds, scores, AI-generated predictions, or other data displayed on the Site.
            </p>
          ),
        },
        {
          heading: "7. Limitation of Liability",
          body: (
            <p>
              To the fullest extent permitted by law, ScoreHub and its operators shall not be liable for any indirect, incidental, or
              consequential damages arising from your use of the Site, including but not limited to decisions made based on content displayed
              here.
            </p>
          ),
        },
        {
          heading: "8. Changes to These Terms",
          body: <p>We may update these Terms from time to time. Continued use of the Site after changes constitutes acceptance of the revised Terms.</p>,
        },
        {
          heading: "9. Contact",
          body: (
            <p>
              For questions about these Terms, please reach out through the{" "}
              <Link href="/community" className="font-bold text-blue-700 underline">
                Community board
              </Link>
              .
            </p>
          ),
        },
      ]}
    />
  );
}
