alter table public.ai_assets add column if not exists display_name text;
insert into public.ai_assets (ai_model, display_name, balance, total_picks, wins, losses, roi)
values ('human', '운영자', 100000, 0, 0, 0, 0)
on conflict (ai_model) do update set display_name = excluded.display_name;

create table if not exists public.cron_runs (
  id bigint generated by default as identity primary key,
  job_name text not null,
  status text not null check (status in ('success','error')),
  started_at timestamptz not null,
  finished_at timestamptz not null default now(),
  details jsonb not null default '{}'::jsonb
);
create index if not exists cron_runs_job_started_idx on public.cron_runs(job_name, started_at desc);
alter table public.cron_runs enable row level security;
grant all privileges on table public.cron_runs to service_role;
grant usage, select on sequence public.cron_runs_id_seq to service_role;
