create extension if not exists pgcrypto;

create table if not exists public.parlays (
  id uuid primary key default gen_random_uuid(),
  ai_model text not null,
  stake numeric not null check (stake > 0),
  total_odds numeric not null check (total_odds > 1),
  status text not null default 'pending' check (status in ('pending', 'won', 'lost')),
  pnl numeric,
  settled_at timestamptz,
  bet_date date not null default (timezone('utc', now()))::date,
  signature text not null,
  created_at timestamptz not null default now(),
  unique (ai_model, bet_date, signature)
);

create table if not exists public.parlay_legs (
  id bigint generated by default as identity primary key,
  parlay_id uuid not null references public.parlays(id) on delete cascade,
  game_id text not null,
  ai_model text not null,
  leg_order integer not null check (leg_order >= 0),
  created_at timestamptz not null default now(),
  unique (parlay_id, game_id)
);

create index if not exists parlays_ai_model_created_at_idx
  on public.parlays (ai_model, created_at desc);
create index if not exists parlays_pending_idx
  on public.parlays (status) where status = 'pending';
create index if not exists parlay_legs_game_ai_idx
  on public.parlay_legs (game_id, ai_model);

alter table public.parlays enable row level security;
alter table public.parlay_legs enable row level security;

drop policy if exists "Public can read parlays" on public.parlays;
create policy "Public can read parlays" on public.parlays for select using (true);
drop policy if exists "Public can read parlay legs" on public.parlay_legs;
create policy "Public can read parlay legs" on public.parlay_legs for select using (true);

comment on table public.parlays is 'AI combination bets. Writes use the server-side service role only.';
comment on table public.parlay_legs is 'Links reusable single picks to combination bets by game and AI model.';
