create table if not exists public.chat_messages (
  id bigint generated by default as identity primary key,
  ai_model text not null check (ai_model in ('gpt', 'gemini', 'claude', 'grok', 'deepseek')),
  message text not null check (char_length(message) between 1 and 500),
  related_game_id text,
  turn_order integer not null check (turn_order >= 0),
  chat_date date not null default (now() at time zone 'utc')::date,
  created_at timestamptz not null default now(),
  unique (chat_date, turn_order)
);

create index if not exists chat_messages_chat_date_idx
  on public.chat_messages (chat_date desc, turn_order asc);

alter table public.chat_messages enable row level security;

drop policy if exists "Public can read chat messages" on public.chat_messages;
create policy "Public can read chat messages"
  on public.chat_messages for select
  to anon, authenticated
  using (true);

grant select on table public.chat_messages to anon, authenticated;
grant all on table public.chat_messages to service_role;
grant usage, select on sequence public.chat_messages_id_seq to service_role;
